# Use an official Node.js runtime as the base image
FROM node:16

# Set the working directory inside the container
WORKDIR /frontend

# Copy the package.json and package-lock.json first to leverage Docker cache
COPY frontend/package*.json ./

# Install required Node.js packages
RUN npm install

# Copy the rest of the frontend code into the container
COPY frontend/ ./

# Start the React development server
CMD ["npm", "start"]