# Use an official Python runtime as the base image
FROM python:3.9-slim

# Set the working directory inside the container
WORKDIR /server

# Copy the backend code into the container
COPY server/ ./

# Install required Python packages
RUN pip3 install --no-cache-dir -r requirements.txt

# Start the Flask app
CMD ["python3", "app.py"]
